ALTER VIEW VerConvites 
AS
SELECT CONV.ID AS 'ID',CONV.SITUACAO AS 'SITUACAO',
EV.ID AS 'ID_EVENTO' , EV.DATA_EVENTO AS 'DATA_EVENTO', EV.NOME AS 'NOME_EVENTO' ,EV.DESCRICAO AS 'DESCRICAO_EVENTO', EV.ACESSO_LIVRE AS 'ACESSO_EVENTO',EV.SITUACAO AS 'SITUACAO_EVENTO',
TE.ID AS 'ID_TIPO_EVENTO',TE.NOME AS 'TIPO_EVENTO',
US.ID AS 'ID_CONVIDADO' ,US.NOME AS 'CONVIDADO', CONV.PALESTRANTE AS 'PALESTRANTE',
INS.ID AS 'INSTITUICAO',INS.NOME_FANTASIA AS 'NOME_INSTITUICAO',INS.LOGRADOURO AS 'LOCAL' ,INS.UF AS 'UF' ,INS.CIDADE AS 'CIDADE',INS.CEP AS 'CEP'

FROM CONVITES AS CONV
INNER JOIN USUARIOS			AS US ON US.ID = CONV.ID_USUARIO
INNER JOIN EVENTOS			AS EV ON EV.ID = CONV.ID_EVENTO
INNER JOIN INSTITUICOES		AS INS ON INS.ID = EV.ID_INSTITUICAO
INNER JOIN TIPOS_EVENTOS	AS TE ON TE.ID = EV.ID_TIPO_EVENTO;
GO
----- PROCEDURES -----

-- RETORNAS CONVITES DO BANCO DE DADOS --
CREATE PROCEDURE VerTodosConvites @PAGINA INT , @QUANTIDADE INT
AS
BEGIN
SELECT *  FROM VerConvites 
ORDER BY DATA_EVENTO DESC
OFFSET @QUANTIDADE ROWS FETCH NEXT @PAGINA ROWS ONLY;
END
GO

--- RETORNA UM CONVITE EM ESPECIFICO DO BANCO DE DADOS --
CREATE PROCEDURE VerConvite @ID INT 
AS
BEGIN
SELECT * FROM VerConvites WHERE ID = @ID;
END
GO

-- RETORNA TODOS OS CONVIDADOS DE UM EVENTO --
CREATE PROCEDURE VerTodosConvidados @ID_EVENTO INT
AS
BEGIN
SELECT *  FROM VerConvites 
WHERE ID_EVENTO = @ID_EVENTO
END
GO

-- RETORNA CONVIDADOS --
CREATE PROCEDURE VerConvidados @ID_EVENTO INT, @PAGINA INT , @QUANTIDADE INT
AS
BEGIN
SELECT *  FROM VerConvites 
WHERE ID_EVENTO = @ID_EVENTO
ORDER BY ID_CONVIDADO DESC
OFFSET @QUANTIDADE ROWS FETCH NEXT @PAGINA ROWS ONLY;
END
GO

-- RETORNA CONVITES DE UM USUARIO --
CREATE PROCEDURE VerMeusConvites @ID INT , @PAGINA INT , @QUANTIDADE INT
AS
BEGIN
SELECT *  FROM VerConvites 
WHERE ID_CONVIDADO = @ID  
ORDER BY DATA_EVENTO DESC
OFFSET @QUANTIDADE ROWS FETCH NEXT @PAGINA ROWS ONLY;
END
GO

-- RETORNA TODOS OS PALESTRANTES DE UM EVENTO --
CREATE PROCEDURE VerPalestrantesEvento @ID_EVENTO INT 
AS
BEGIN
SELECT * FROM VerConvites WHERE ID_EVENTO = @ID_EVENTO AND PALESTRANTE = 1; 
END
GO

-- RETORNA OS EVENTOS EM QUE UM USUARIO EM ESPECIFICO É PALESTRANTE --
CREATE PROCEDURE VerMinhasPalestras @ID INT , @PAGINA INT , @QUANTIDADE INT
AS
BEGIN
SELECT *  FROM VerConvites 
WHERE ID_CONVIDADO = @ID AND PALESTRANTE = 1  
ORDER BY DATA_EVENTO DESC
OFFSET @QUANTIDADE ROWS FETCH NEXT @PAGINA ROWS ONLY;
END
GO