CREATE VIEW VerEventos
AS
SELECT 
EV.ID 'EVENTO',EV.NOME AS 'NOME_EVENTO' ,EV.DESCRICAO AS 'DESCRICAO', EV.DATA_EVENTO AS 'DATA_EVENTO', EV.ACESSO_LIVRE AS 'ACESSO_LIVRE', EV.SITUACAO AS 'SITUACAO',
TE.ID AS 'TIPO_EVENTO', TE.NOME AS 'NOME_TIPO_EVENTO' ,
INS.ID AS 'INSTITUICAO',INS.NOME_FANTASIA AS 'NOME_INSTITUICAO',INS.LOGRADOURO AS 'LOCAL' ,INS.UF AS 'UF' ,INS.CIDADE AS 'CIDADE',INS.CEP AS 'CEP'
FROM EVENTOS AS EV
LEFT JOIN INSTITUICOES AS INS ON INS.ID = EV.ID_INSTITUICAO
LEFT JOIN TIPOS_EVENTOS AS TE ON TE.ID = EV.ID_TIPO_EVENTO ;
GO

  --- EVENTOS ---
CREATE PROCEDURE VerEvento @ID INT 
AS
BEGIN
SELECT * FROM VerEventos WHERE ID = @ID;
END
GO

CREATE PROCEDURE VerEventosPorTipo @TIPO_EVENTO INT 
AS
BEGIN
SELECT * FROM VerEventos WHERE TIPO_EVENTO = @TIPO_EVENTO;
END
GO

CREATE PROCEDURE VerEventosDeInstituicao @INSTITUICAO INT 
AS
BEGIN
SELECT * FROM VerEventos WHERE INSTITUICAO = @INSTITUICAO;
END
GO

CREATE PROCEDURE VerEventosEntreDatas @DATA_INICAL DATETIME , @DATA_FINAL DATETIME
AS
BEGIN
SELECT * FROM VerEventos WHERE DATA_EVENTO BETWEEN @DATA_INICAL AND @DATA_FINAL ORDER BY DATA_EVENTO ASC;
END
GO