  --- INSTITUIÇÕES ---
CREATE PROCEDURE VerInstituicao @ID INT 
AS
BEGIN
SELECT ID , NOME_FANTASIA ,CIDADE , UF , CEP , LOGRADOURO FROM INSTITUICOES WHERE ID = @ID;
END
GO

CREATE PROCEDURE VerInstituicoes @NOME_FANTASIA VARCHAR(250) 
AS
BEGIN
SELECT * FROM INSTITUICOES WHERE NOME_FANTASIA LIKE '%' + @NOME_FANTASIA + '%'; 
END 
GO

