--Criar banco de dados
CREATE DATABASE PROJETO_SVIGUFO;

/*Abre o banco de dados*/
USE PROJETO_SVIGUFO;

--Cria uma tabela com tipos de evento
CREATE TABLE TIPOS_EVENTOS(
	ID INT IDENTITY PRIMARY KEY, --Setando ID como chave primaria
	NOME VARCHAR(100) UNIQUE NOT NULL--Seta o nome do tipo de evento , que deverá ser unico e nao poderá ser nulo
);
/*Cria a tabela com as instituições*/
CREATE TABLE INSTITUICOES(
	ID INT IDENTITY PRIMARY KEY,
	NOME_FANTASIA VARCHAR(250) UNIQUE NOT NULL,
	RAZAO_SOCIAL VARCHAR(250) UNIQUE NOT NULL,
	CNPJ CHAR(14) UNIQUE NOT NULL,
	LOGRADOURO VARCHAR(300),
	CEP CHAR(8) NOT NULL,
	UF CHAR(2) NOT NULL,/*Seta uma string com valor fixo de 2 caracteres (utilizado quando se tem certeza absoluta do tamanho da string inserida)*/
	CIDADE VARCHAR(250) NOT NULL
);

CREATE TABLE EVENTOS(
	/*PRIMARY KEY porque será reconhecida a partir deste valor*/
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(250) NOT NULL,
	DESCRICAO TEXT NOT NULL,/*TEXT = um varchar grande e sem limite de caracteres*/
	DATA_EVENTO DATETIME NOT NULL,
	ACESSO_LIVRE BIT DEFAULT(1),
	SITUACAO INT NOT NULL,
	ID_INSTITUICAO INT FOREIGN KEY REFERENCES INSTITUICOES(ID)NOT NULL,
	ID_TIPO_EVENTO INT FOREIGN KEY REFERENCES TIPOS_EVENTOS(ID)NOT NULL,
);

CREATE TABLE USUARIOS(
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(250) NOT NULL,
	EMAIL VARCHAR(250) NOT NULL UNIQUE,
	SENHA VARCHAR(50) NOT NULL,
	TIPO_USUARIO INT NOT NULL
);

CREATE TABLE CONVITES(
	ID INT IDENTITY PRIMARY KEY,
	ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID)NOT NULL,--MANEIRA DECENTE DE CRIAR CHAVE ESTRANGEIRA ;-;
	ID_EVENTO INT FOREIGN KEY REFERENCES EVENTOS(ID)NOT NULL,
	SITUACAO INT NOT NULL
);
