CREATE PROCEDURE CriarEvento
	@NOME VARCHAR(250),
	@DESCRICAO TEXT,
	@DATA_EVENTO DATETIME,
	@ACESSO_LIVRE BIT,
	@SITUACAO INT,
	@ID_INSTITUICAO INT,
	@ID_TIPO_EVENTO INT
AS 
BEGIN 
INSERT INTO 
EVENTOS(NOME,DESCRICAO,DATA_EVENTO,ACESSO_LIVRE,SITUACAO,ID_INSTITUICAO,ID_TIPO_EVENTO) 
VALUES(@NOME,@DESCRICAO,@DATA_EVENTO,@ACESSO_LIVRE,@SITUACAO,@ID_INSTITUICAO,@ID_TIPO_EVENTO);
END
GO

CREATE PROCEDURE CriarInstituicao
	@NOME_FANTASIA VARCHAR(250),
	@RAZAO_SOCIAL VARCHAR(250),
	@CNPJ CHAR(14),
	@LOGRADOURO VARCHAR(300),
	@CEP CHAR(8),
	@UF CHAR(2),
	@CIDADE VARCHAR(250)
AS
BEGIN
INSERT INTO
INSTITUICOES(NOME_FANTASIA,RAZAO_SOCIAL,CNPJ,LOGRADOURO,CEP,UF,CIDADE)
VALUES(@NOME_FANTASIA,@RAZAO_SOCIAL,@CNPJ,@LOGRADOURO,@CEP,@UF,@CIDADE);
END
GO

CREATE PROCEDURE CriarUsuario 
	@NOME VARCHAR(250),
	@EMAIL VARCHAR(250),
	@SENHA VARCHAR(50),
	@TIPO_USUARIO INT
AS
BEGIN
INSERT INTO 
USUARIOS(NOME,EMAIL,SENHA,TIPO_USUARIO)
VALUES(@NOME,@EMAIL,@SENHA,@TIPO_USUARIO);
END
GO

CREATE PROCEDURE CriarTipoEvento
	@NOME VARCHAR(100)
AS
BEGIN
INSERT INTO 
TIPOS_EVENTOS(NOME)
VALUES(@NOME);
END
GO

CREATE PROCEDURE CriarConvite 	
	@ID_USUARIO INT,
	@ID_EVENTO INT,
	@SITUACAO INT
AS
BEGIN
INSERT INTO
CONVITES(ID_USUARIO,ID_EVENTO,SITUACAO)
VALUES(@ID_USUARIO,@ID_EVENTO,@SITUACAO);
END
GO
